services:
    inquies.pokerth.controller:
        class: inquies\pokerth\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'