services:
    inquies.pokerth.controller:
        class: inquies\pokerth\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
    inquies.pokerth.listener:
        arguments:
            - '@dbal.conn'
            - '@request'
        class: inquies\pokerth\event\listener
        tags:
            - { name: event.listener }