<?php
/**
 * Länderliste für Flaggen und das Country-Feld im UCP-Profil.
 *
 * Schlüssel ist der Wert, der in pokerth_ranking.player.country_iso steht
 * (kleingeschrieben). "svg" ist der Dateiname unter images/flags/ — der weicht
 * bei England, Schottland und Wales vom gespeicherten Wert ab.
 *
 * Erzeugt aus pthranking/resources/js/countries.js.
 */

return [
    'ad'           => ['svg' => 'ad'        , 'title' => 'Andorra'],
    'ae'           => ['svg' => 'ae'        , 'title' => 'United Arab Emirates'],
    'af'           => ['svg' => 'af'        , 'title' => 'Afghanistan'],
    'ag'           => ['svg' => 'ag'        , 'title' => 'Antigua and Barbuda'],
    'ai'           => ['svg' => 'ai'        , 'title' => 'Anguilla'],
    'al'           => ['svg' => 'al'        , 'title' => 'Albania'],
    'am'           => ['svg' => 'am'        , 'title' => 'Armenia'],
    'an'           => ['svg' => 'an'        , 'title' => 'Netherlands Antilles'],
    'ao'           => ['svg' => 'ao'        , 'title' => 'Angola'],
    'ar'           => ['svg' => 'ar'        , 'title' => 'Argentina'],
    'as'           => ['svg' => 'as'        , 'title' => 'American Samoa'],
    'at'           => ['svg' => 'at'        , 'title' => 'Austria'],
    'au'           => ['svg' => 'au'        , 'title' => 'Australia'],
    'aw'           => ['svg' => 'aw'        , 'title' => 'Aruba'],
    'ax'           => ['svg' => 'ax'        , 'title' => 'Åland Islands'],
    'az'           => ['svg' => 'az'        , 'title' => 'Azerbaijan'],
    'ba'           => ['svg' => 'ba'        , 'title' => 'Bosnia and Herzegovina'],
    'bb'           => ['svg' => 'bb'        , 'title' => 'Barbados'],
    'bd'           => ['svg' => 'bd'        , 'title' => 'Bangladesh'],
    'be'           => ['svg' => 'be'        , 'title' => 'Belgium'],
    'bf'           => ['svg' => 'bf'        , 'title' => 'Burkina Faso'],
    'bg'           => ['svg' => 'bg'        , 'title' => 'Bulgaria'],
    'bh'           => ['svg' => 'bh'        , 'title' => 'Bahrain'],
    'bi'           => ['svg' => 'bi'        , 'title' => 'Burundi'],
    'bj'           => ['svg' => 'bj'        , 'title' => 'Benin'],
    'bm'           => ['svg' => 'bm'        , 'title' => 'Bermuda'],
    'bn'           => ['svg' => 'bn'        , 'title' => 'Brunei Darussalam'],
    'bo'           => ['svg' => 'bo'        , 'title' => 'Bolivia (Plurinational State of)'],
    'br'           => ['svg' => 'br'        , 'title' => 'Brazil'],
    'bs'           => ['svg' => 'bs'        , 'title' => 'Bahamas'],
    'bt'           => ['svg' => 'bt'        , 'title' => 'Bhutan'],
    'bv'           => ['svg' => 'bv'        , 'title' => 'Bouvet Island'],
    'bw'           => ['svg' => 'bw'        , 'title' => 'Botswana'],
    'by'           => ['svg' => 'by'        , 'title' => 'Belarus'],
    'bz'           => ['svg' => 'bz'        , 'title' => 'Belize'],
    'ca'           => ['svg' => 'ca'        , 'title' => 'Canada'],
    'catalonia'    => ['svg' => 'catalonia' , 'title' => 'Catalonia'],
    'cc'           => ['svg' => 'cc'        , 'title' => 'Cocos (Keeling) Islands'],
    'cd'           => ['svg' => 'cd'        , 'title' => 'Congo, Democratic Republic of the'],
    'cf'           => ['svg' => 'cf'        , 'title' => 'Central African Republic'],
    'cg'           => ['svg' => 'cg'        , 'title' => 'Congo'],
    'ch'           => ['svg' => 'ch'        , 'title' => 'Switzerland'],
    'ci'           => ['svg' => 'ci'        , 'title' => 'Côte d\'Ivoire'],
    'ck'           => ['svg' => 'ck'        , 'title' => 'Cook Islands'],
    'cl'           => ['svg' => 'cl'        , 'title' => 'Chile'],
    'cm'           => ['svg' => 'cm'        , 'title' => 'Cameroon'],
    'cn'           => ['svg' => 'cn'        , 'title' => 'China'],
    'co'           => ['svg' => 'co'        , 'title' => 'Colombia'],
    'cr'           => ['svg' => 'cr'        , 'title' => 'Costa Rica'],
    'cu'           => ['svg' => 'cu'        , 'title' => 'Cuba'],
    'cv'           => ['svg' => 'cv'        , 'title' => 'Cabo Verde'],
    'cx'           => ['svg' => 'cx'        , 'title' => 'Christmas Island'],
    'cy'           => ['svg' => 'cy'        , 'title' => 'Cyprus'],
    'cz'           => ['svg' => 'cz'        , 'title' => 'Czechia'],
    'de'           => ['svg' => 'de'        , 'title' => 'Germany'],
    'dj'           => ['svg' => 'dj'        , 'title' => 'Djibouti'],
    'dk'           => ['svg' => 'dk'        , 'title' => 'Denmark'],
    'dm'           => ['svg' => 'dm'        , 'title' => 'Dominica'],
    'do'           => ['svg' => 'do'        , 'title' => 'Dominican Republic'],
    'dz'           => ['svg' => 'dz'        , 'title' => 'Algeria'],
    'ec'           => ['svg' => 'ec'        , 'title' => 'Ecuador'],
    'ee'           => ['svg' => 'ee'        , 'title' => 'Estonia'],
    'eg'           => ['svg' => 'eg'        , 'title' => 'Egypt'],
    'eh'           => ['svg' => 'eh'        , 'title' => 'Western Sahara'],
    'england'      => ['svg' => 'gb-eng'    , 'title' => 'England'],
    'er'           => ['svg' => 'er'        , 'title' => 'Eritrea'],
    'es'           => ['svg' => 'es'        , 'title' => 'Spain'],
    'et'           => ['svg' => 'et'        , 'title' => 'Ethiopia'],
    'europeanunion' => ['svg' => 'europeanunion', 'title' => 'European Union'],
    'fam'          => ['svg' => 'fam'       , 'title' => ''],
    'fi'           => ['svg' => 'fi'        , 'title' => 'Finland'],
    'fj'           => ['svg' => 'fj'        , 'title' => 'Fiji'],
    'fk'           => ['svg' => 'fk'        , 'title' => 'Falkland Islands (Malvinas)'],
    'fm'           => ['svg' => 'fm'        , 'title' => 'Micronesia (Federated States of)'],
    'fo'           => ['svg' => 'fo'        , 'title' => 'Faroe Islands'],
    'fr'           => ['svg' => 'fr'        , 'title' => 'France'],
    'ga'           => ['svg' => 'ga'        , 'title' => 'Gabon'],
    'gb'           => ['svg' => 'gb'        , 'title' => 'United Kingdom of Great Britain and Northern Ireland'],
    'gd'           => ['svg' => 'gd'        , 'title' => 'Grenada'],
    'ge'           => ['svg' => 'ge'        , 'title' => 'Georgia'],
    'gf'           => ['svg' => 'gf'        , 'title' => 'French Guiana'],
    'gh'           => ['svg' => 'gh'        , 'title' => 'Ghana'],
    'gi'           => ['svg' => 'gi'        , 'title' => 'Gibraltar'],
    'gl'           => ['svg' => 'gl'        , 'title' => 'Greenland'],
    'gm'           => ['svg' => 'gm'        , 'title' => 'Gambia'],
    'gn'           => ['svg' => 'gn'        , 'title' => 'Guinea'],
    'gp'           => ['svg' => 'gp'        , 'title' => 'Guadeloupe'],
    'gq'           => ['svg' => 'gq'        , 'title' => 'Equatorial Guinea'],
    'gr'           => ['svg' => 'gr'        , 'title' => 'Greece'],
    'gs'           => ['svg' => 'gs'        , 'title' => 'South Georgia and the South Sandwich Islands'],
    'gt'           => ['svg' => 'gt'        , 'title' => 'Guatemala'],
    'gu'           => ['svg' => 'gu'        , 'title' => 'Guam'],
    'gw'           => ['svg' => 'gw'        , 'title' => 'Guinea-Bissau'],
    'gy'           => ['svg' => 'gy'        , 'title' => 'Guyana'],
    'hk'           => ['svg' => 'hk'        , 'title' => 'Hong Kong'],
    'hm'           => ['svg' => 'hm'        , 'title' => 'Heard Island and McDonald Islands'],
    'hn'           => ['svg' => 'hn'        , 'title' => 'Honduras'],
    'hr'           => ['svg' => 'hr'        , 'title' => 'Croatia'],
    'ht'           => ['svg' => 'ht'        , 'title' => 'Haiti'],
    'hu'           => ['svg' => 'hu'        , 'title' => 'Hungary'],
    'id'           => ['svg' => 'id'        , 'title' => 'Indonesia'],
    'ie'           => ['svg' => 'ie'        , 'title' => 'Ireland'],
    'il'           => ['svg' => 'il'        , 'title' => 'Israel'],
    'in'           => ['svg' => 'in'        , 'title' => 'India'],
    'io'           => ['svg' => 'io'        , 'title' => 'British Indian Ocean Territory'],
    'iq'           => ['svg' => 'iq'        , 'title' => 'Iraq'],
    'ir'           => ['svg' => 'ir'        , 'title' => 'Iran (Islamic Republic of)'],
    'is'           => ['svg' => 'is'        , 'title' => 'Iceland'],
    'it'           => ['svg' => 'it'        , 'title' => 'Italy'],
    'jm'           => ['svg' => 'jm'        , 'title' => 'Jamaica'],
    'jo'           => ['svg' => 'jo'        , 'title' => 'Jordan'],
    'jp'           => ['svg' => 'jp'        , 'title' => 'Japan'],
    'ke'           => ['svg' => 'ke'        , 'title' => 'Kenya'],
    'kg'           => ['svg' => 'kg'        , 'title' => 'Kyrgyzstan'],
    'kh'           => ['svg' => 'kh'        , 'title' => 'Cambodia'],
    'ki'           => ['svg' => 'ki'        , 'title' => 'Kiribati'],
    'km'           => ['svg' => 'km'        , 'title' => 'Comoros'],
    'kn'           => ['svg' => 'kn'        , 'title' => 'Saint Kitts and Nevis'],
    'kp'           => ['svg' => 'kp'        , 'title' => 'Korea (Democratic People\'s Republic of)'],
    'kr'           => ['svg' => 'kr'        , 'title' => 'Korea, Republic of'],
    'kw'           => ['svg' => 'kw'        , 'title' => 'Kuwait'],
    'ky'           => ['svg' => 'ky'        , 'title' => 'Cayman Islands'],
    'kz'           => ['svg' => 'kz'        , 'title' => 'Kazakhstan'],
    'la'           => ['svg' => 'la'        , 'title' => 'Lao People\'s Democratic Republic'],
    'lb'           => ['svg' => 'lb'        , 'title' => 'Lebanon'],
    'lc'           => ['svg' => 'lc'        , 'title' => 'Saint Lucia'],
    'li'           => ['svg' => 'li'        , 'title' => 'Liechtenstein'],
    'lk'           => ['svg' => 'lk'        , 'title' => 'Sri Lanka'],
    'lr'           => ['svg' => 'lr'        , 'title' => 'Liberia'],
    'ls'           => ['svg' => 'ls'        , 'title' => 'Lesotho'],
    'lt'           => ['svg' => 'lt'        , 'title' => 'Lithuania'],
    'lu'           => ['svg' => 'lu'        , 'title' => 'Luxembourg'],
    'lv'           => ['svg' => 'lv'        , 'title' => 'Latvia'],
    'ly'           => ['svg' => 'ly'        , 'title' => 'Libya'],
    'ma'           => ['svg' => 'ma'        , 'title' => 'Morocco'],
    'mc'           => ['svg' => 'mc'        , 'title' => 'Monaco'],
    'md'           => ['svg' => 'md'        , 'title' => 'Moldova, Republic of'],
    'me'           => ['svg' => 'me'        , 'title' => 'Montenegro'],
    'mg'           => ['svg' => 'mg'        , 'title' => 'Madagascar'],
    'mh'           => ['svg' => 'mh'        , 'title' => 'Marshall Islands'],
    'mk'           => ['svg' => 'mk'        , 'title' => 'North Macedonia'],
    'ml'           => ['svg' => 'ml'        , 'title' => 'Mali'],
    'mm'           => ['svg' => 'mm'        , 'title' => 'Myanmar'],
    'mn'           => ['svg' => 'mn'        , 'title' => 'Mongolia'],
    'mo'           => ['svg' => 'mo'        , 'title' => 'Macao'],
    'mp'           => ['svg' => 'mp'        , 'title' => 'Northern Mariana Islands'],
    'mq'           => ['svg' => 'mq'        , 'title' => 'Martinique'],
    'mr'           => ['svg' => 'mr'        , 'title' => 'Mauritania'],
    'ms'           => ['svg' => 'ms'        , 'title' => 'Montserrat'],
    'mt'           => ['svg' => 'mt'        , 'title' => 'Malta'],
    'mu'           => ['svg' => 'mu'        , 'title' => 'Mauritius'],
    'mv'           => ['svg' => 'mv'        , 'title' => 'Maldives'],
    'mw'           => ['svg' => 'mw'        , 'title' => 'Malawi'],
    'mx'           => ['svg' => 'mx'        , 'title' => 'Mexico'],
    'my'           => ['svg' => 'my'        , 'title' => 'Malaysia'],
    'mz'           => ['svg' => 'mz'        , 'title' => 'Mozambique'],
    'na'           => ['svg' => 'na'        , 'title' => 'Namibia'],
    'nc'           => ['svg' => 'nc'        , 'title' => 'New Caledonia'],
    'ne'           => ['svg' => 'ne'        , 'title' => 'Niger'],
    'nf'           => ['svg' => 'nf'        , 'title' => 'Norfolk Island'],
    'ng'           => ['svg' => 'ng'        , 'title' => 'Nigeria'],
    'ni'           => ['svg' => 'ni'        , 'title' => 'Nicaragua'],
    'nl'           => ['svg' => 'nl'        , 'title' => 'Netherlands'],
    'no'           => ['svg' => 'no'        , 'title' => 'Norway'],
    'np'           => ['svg' => 'np'        , 'title' => 'Nepal'],
    'nr'           => ['svg' => 'nr'        , 'title' => 'Nauru'],
    'nu'           => ['svg' => 'nu'        , 'title' => 'Niue'],
    'nz'           => ['svg' => 'nz'        , 'title' => 'New Zealand'],
    'om'           => ['svg' => 'om'        , 'title' => 'Oman'],
    'pa'           => ['svg' => 'pa'        , 'title' => 'Panama'],
    'pe'           => ['svg' => 'pe'        , 'title' => 'Peru'],
    'pf'           => ['svg' => 'pf'        , 'title' => 'French Polynesia'],
    'pg'           => ['svg' => 'pg'        , 'title' => 'Papua New Guinea'],
    'ph'           => ['svg' => 'ph'        , 'title' => 'Philippines'],
    'pk'           => ['svg' => 'pk'        , 'title' => 'Pakistan'],
    'pl'           => ['svg' => 'pl'        , 'title' => 'Poland'],
    'pm'           => ['svg' => 'pm'        , 'title' => 'Saint Pierre and Miquelon'],
    'pn'           => ['svg' => 'pn'        , 'title' => 'Pitcairn'],
    'pr'           => ['svg' => 'pr'        , 'title' => 'Puerto Rico'],
    'ps'           => ['svg' => 'ps'        , 'title' => 'Palestine, State of'],
    'pt'           => ['svg' => 'pt'        , 'title' => 'Portugal'],
    'pw'           => ['svg' => 'pw'        , 'title' => 'Palau'],
    'py'           => ['svg' => 'py'        , 'title' => 'Paraguay'],
    'qa'           => ['svg' => 'qa'        , 'title' => 'Qatar'],
    're'           => ['svg' => 're'        , 'title' => 'Réunion'],
    'ro'           => ['svg' => 'ro'        , 'title' => 'Romania'],
    'rs'           => ['svg' => 'rs'        , 'title' => 'Serbia'],
    'ru'           => ['svg' => 'ru'        , 'title' => 'Russian Federation'],
    'rw'           => ['svg' => 'rw'        , 'title' => 'Rwanda'],
    'sa'           => ['svg' => 'sa'        , 'title' => 'Saudi Arabia'],
    'sb'           => ['svg' => 'sb'        , 'title' => 'Solomon Islands'],
    'sc'           => ['svg' => 'sc'        , 'title' => 'Seychelles'],
    'scotland'     => ['svg' => 'gb-sct'    , 'title' => 'Scotland'],
    'sd'           => ['svg' => 'sd'        , 'title' => 'Sudan'],
    'se'           => ['svg' => 'se'        , 'title' => 'Sweden'],
    'sg'           => ['svg' => 'sg'        , 'title' => 'Singapore'],
    'sh'           => ['svg' => 'sh'        , 'title' => 'Saint Helena, Ascension and Tristan da Cunha'],
    'si'           => ['svg' => 'si'        , 'title' => 'Slovenia'],
    'sj'           => ['svg' => 'sj'        , 'title' => 'Svalbard and Jan Mayen'],
    'sk'           => ['svg' => 'sk'        , 'title' => 'Slovakia'],
    'sl'           => ['svg' => 'sl'        , 'title' => 'Sierra Leone'],
    'sm'           => ['svg' => 'sm'        , 'title' => 'San Marino'],
    'sn'           => ['svg' => 'sn'        , 'title' => 'Senegal'],
    'so'           => ['svg' => 'so'        , 'title' => 'Somalia'],
    'sr'           => ['svg' => 'sr'        , 'title' => 'Suriname'],
    'st'           => ['svg' => 'st'        , 'title' => 'Sao Tome and Principe'],
    'sv'           => ['svg' => 'sv'        , 'title' => 'El Salvador'],
    'sy'           => ['svg' => 'sy'        , 'title' => 'Syrian Arab Republic'],
    'sz'           => ['svg' => 'sz'        , 'title' => 'Eswatini'],
    'tc'           => ['svg' => 'tc'        , 'title' => 'Turks and Caicos Islands'],
    'td'           => ['svg' => 'td'        , 'title' => 'Chad'],
    'tf'           => ['svg' => 'tf'        , 'title' => 'French Southern Territories'],
    'tg'           => ['svg' => 'tg'        , 'title' => 'Togo'],
    'th'           => ['svg' => 'th'        , 'title' => 'Thailand'],
    'tj'           => ['svg' => 'tj'        , 'title' => 'Tajikistan'],
    'tk'           => ['svg' => 'tk'        , 'title' => 'Tokelau'],
    'tl'           => ['svg' => 'tl'        , 'title' => 'Timor-Leste'],
    'tm'           => ['svg' => 'tm'        , 'title' => 'Turkmenistan'],
    'tn'           => ['svg' => 'tn'        , 'title' => 'Tunisia'],
    'to'           => ['svg' => 'to'        , 'title' => 'Tonga'],
    'tr'           => ['svg' => 'tr'        , 'title' => 'Turkey'],
    'tt'           => ['svg' => 'tt'        , 'title' => 'Trinidad and Tobago'],
    'tv'           => ['svg' => 'tv'        , 'title' => 'Tuvalu'],
    'tw'           => ['svg' => 'tw'        , 'title' => 'Taiwan, Province of China'],
    'tz'           => ['svg' => 'tz'        , 'title' => 'Tanzania, United Republic of'],
    'ua'           => ['svg' => 'ua'        , 'title' => 'Ukraine'],
    'ug'           => ['svg' => 'ug'        , 'title' => 'Uganda'],
    'um'           => ['svg' => 'um'        , 'title' => 'United States Minor Outlying Islands'],
    'us'           => ['svg' => 'us'        , 'title' => 'United States of America'],
    'uy'           => ['svg' => 'uy'        , 'title' => 'Uruguay'],
    'uz'           => ['svg' => 'uz'        , 'title' => 'Uzbekistan'],
    'va'           => ['svg' => 'va'        , 'title' => 'Holy See'],
    'vc'           => ['svg' => 'vc'        , 'title' => 'Saint Vincent and the Grenadines'],
    've'           => ['svg' => 've'        , 'title' => 'Venezuela (Bolivarian Republic of)'],
    'vg'           => ['svg' => 'vg'        , 'title' => 'Virgin Islands (British)'],
    'vi'           => ['svg' => 'vi'        , 'title' => 'Virgin Islands (U.S.)'],
    'vn'           => ['svg' => 'vn'        , 'title' => 'Viet Nam'],
    'vu'           => ['svg' => 'vu'        , 'title' => 'Vanuatu'],
    'wales'        => ['svg' => 'gb-wls'    , 'title' => 'Wales'],
    'wf'           => ['svg' => 'wf'        , 'title' => 'Wallis and Futuna'],
    'ws'           => ['svg' => 'ws'        , 'title' => 'Samoa'],
    'ye'           => ['svg' => 'ye'        , 'title' => 'Yemen'],
    'yt'           => ['svg' => 'yt'        , 'title' => 'Mayotte'],
    'za'           => ['svg' => 'za'        , 'title' => 'South Africa'],
    'zm'           => ['svg' => 'zm'        , 'title' => 'Zambia'],
    'zw'           => ['svg' => 'zw'        , 'title' => 'Zimbabwe'],
];
